instruments:
- BTC/USD
- ETH/USD
- SOL/USD
- BNB/USD
- AVAX/USD
- LUNA/USD
- DOGE/USD
- LTC/USD
- FTT/USD
- AXS/USD
- XRP/USD
- SPELL/USD
- LOOKS/USD
- AAVE/USD
- DOT/USD
- ATOM/USD
- MATIC/USD
- SUSHI/USD
- LINK/USD
- FTM/USD
- RUNE/USD
- SRM/USD
- FXS/USD
- RAY/USD
- SAND/USD
- APE/USD
- STG/USD
- SHIB/USD
- SLP/USD
- DAI/USD
- UST/USD
- WAVES/USD
- SXP/USD
- DYDX/USD
- IMX/USD
- KNC/USD
- OMG/USD
- TRX/USD
- BICO/USD
- GMT/USD
- CRV/USD
- UNI/USD
- STEP/USD
- BCH/USD
- ATLAS/USD
- MCB/USD
- 1INCH/USD
- HNT/USD
- GRT/USD
- MANA/USD
- BULL/USD
- GALA/USD
- ETHBULL/USD
- PERP/USD
- GENE/USD
- POLIS/USD
- LRC/USD
- CRO/USD
- RNDR/USD
- BRZ/USD
- WBTC/USD
- BAT/USD
- ALPHA/USD
- CTX/USD
- ENS/USD
- COMP/USD
- BNT/USD
- CVX/USD
- VGX/USD
- AUDIO/USD
- MATICBULL/USD
- YFI/USD
- BEAR/USD
- BIT/USD
- FIDA/USD
- SNX/USD
- KSHIB/USD
- BOBA/USD
- CHZ/USD
- GODS/USD
- SKL/USD
- EUR/USD
- ZRX/USD
- TONCOIN/USD
- RSR/USD
- ATOMBULL/USD
- DOGEBULL/USD
- KBTT/USD
- HT/USD
- REN/USD
- CREAM/USD
- QI/USD
- BADGER/USD
- CLV/USD
- JOE/USD
- CONV/USD
- CEL/USD
- ENJ/USD
- STETH/USD
- ADABULL/USD
